--Creating Warehouse

CREATE OR REPLACE WAREHOUSE NISSAN_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

SHOW WAREHOUSES;

--------------------------------
--Creating Database

CREATE OR REPLACE DATABASE NISSAN_ANALYTICS;

USE DATABASE NISSAN_ANALYTICS;

SHOW DATABASES;

----------------------------------
--Creating Schemas

CREATE OR REPLACE SCHEMA RAW;

CREATE OR REPLACE SCHEMA SILVER;

CREATE OR REPLACE SCHEMA GOLD;

SHOW SCHEMAS;
