USE SCHEMA RAW;
SELECT COUNT(*)
FROM RAW.RAW_SALES; --COUNT IS 100

--CHECKING FOR NULLS
SELECT
    COUNT_IF(f.value:sale_id IS NULL) AS NULL_SALE_ID,
    COUNT_IF(f.value:customer_id IS NULL) AS NULL_CUSTOMER_ID,
    COUNT_IF(f.value:dealer_id IS NULL) AS NULL_DEALER_ID,
    COUNT_IF(f.value:vehicle_id IS NULL) AS NULL_VEHICLE_ID
FROM RAW.RAW_SALES,
LATERAL FLATTEN(INPUT => RAW_RECORD) f;

--DUPLICATE CHECK
SELECT
    f.value:sale_id::STRING,
    COUNT(*)
FROM RAW.RAW_SALES,
LATERAL FLATTEN(INPUT => RAW_RECORD) f
GROUP BY 1
HAVING COUNT(*) > 1;

SELECT
    f.value:sale_id::STRING AS SALE_ID,
    COUNT(*) AS CNT
FROM RAW.RAW_SALES,
LATERAL FLATTEN(INPUT => RAW_RECORD) f
GROUP BY 1
HAVING COUNT(*) > 1;

--Missing Foreign Keys CHECK (EXTRA DEALER ID IN SALES COMPARED TO DEALER MASTER)
SELECT DISTINCT
    s.DEALER_ID
FROM SILVER.SALES s
LEFT JOIN SILVER.DEALERS d
ON s.DEALER_ID = d.DEALER_ID
WHERE d.DEALER_ID IS NULL;

--CHECKING IF THERE ARE NEGATIVE VALUES AND DATE IS MORE THAN TODAYS DATE
SELECT *
FROM SILVER.SALES
WHERE QUANTITY <= 0;

SELECT *
FROM SILVER.SALES
WHERE UNIT_PRICE <= 0;

SELECT *
FROM SILVER.DEALERS
WHERE OPENING_YEAR > YEAR(CURRENT_DATE());

--CHECKING IF NAMES ARE STANDARDIZED LIKE US, USA, AMERICA etc
SELECT DISTINCT COUNTRY
FROM SILVER.DEALERS
ORDER BY COUNTRY;

--CHECKING WHITE SPACES
SELECT *
FROM SILVER.DEALERS
WHERE DEALER_NAME <> TRIM(DEALER_NAME);

--DATE VALIDATION
SELECT *
FROM SILVER.SALES
WHERE SALE_DATE > CURRENT_DATE();

--CEHCKING COUNT FOR SALES CHANNELS, FOUND THERE IS AN UNKNOWN
SELECT SALES_CHANNEL,
COUNT(*)
FROM SILVER.SALES
GROUP BY SALES_CHANNEL;