CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE OR REPLACE TABLE GOLD.DIM_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    COUNTRY,
    CUSTOMER_TYPE,
    LOYALTY_TIER,
    REGISTRATION_DATE

FROM SILVER.CUSTOMERS;

SELECT *
FROM GOLD.DIM_CUSTOMERS
LIMIT 10;

CREATE OR REPLACE TABLE GOLD.DIM_DEALERS AS
SELECT
    DEALER_ID,
    DEALER_NAME,
    COUNTRY,
    CITY,
    REGION,
    DEALERSHIP_TYPE,
    OPENING_YEAR

FROM SILVER.DEALERS;

SELECT *
FROM GOLD.DIM_DEALERS
LIMIT 10;

CREATE OR REPLACE TABLE GOLD.DIM_VEHICLES AS

SELECT
    VEHICLE_ID,
    VEHICLE_MODEL,
    VEHICLE_TYPE,
    FUEL_TYPE,
    BASE_PRICE_USD,
    LAUNCH_YEAR,
    STATUS

FROM SILVER.VEHICLES;

SELECT *
FROM GOLD.DIM_VEHICLES
LIMIT 10;


CREATE OR REPLACE TABLE GOLD.FACT_SALES AS

SELECT
    SALE_ID,
    CUSTOMER_ID,
    DEALER_ID,
    VEHICLE_ID,
    SALE_DATE,
    SALES_CHANNEL,
    QUANTITY,
    UNIT_PRICE,
    QUANTITY * UNIT_PRICE AS TOTAL_AMOUNT

FROM SILVER.SALES;

SELECT COUNT(*)
FROM GOLD.FACT_SALES;

SELECT *
FROM GOLD.FACT_SALES
LIMIT 10;

---Data Warehouse Testing
---We are checking if everything is as expected and validate
SELECT
    SUM(QUANTITY * UNIT_PRICE) AS SILVER_REVENUE
FROM SILVER.SALES;

SELECT
    SUM(TOTAL_AMOUNT) AS GOLD_REVENUE
FROM GOLD.FACT_SALES;

---Both revenue match, then this is good

---Checking if there is any null customer_ids between dim and fact table
SELECT COUNT(*)
FROM GOLD.FACT_SALES f
LEFT JOIN GOLD.DIM_CUSTOMERS c
ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL;

--- similarly we will check for dealers, vehicle etc etc this is known as integrity check

SELECT COUNT(*)
FROM GOLD.FACT_SALES f
LEFT JOIN GOLD.DIM_DEALERS d
ON f.DEALER_ID = d.DEALER_ID
WHERE d.DEALER_ID IS NULL;

SELECT COUNT(*)
FROM GOLD.FACT_SALES f
LEFT JOIN GOLD.DIM_VEHICLES v
ON f.VEHICLE_ID = v.VEHICLE_ID
WHERE v.VEHICLE_ID IS NULL;

---Checking duplicate sales IDs
SELECT
SALE_ID,
COUNT(*)
FROM GOLD.FACT_SALES
GROUP BY SALE_ID
HAVING COUNT(*) > 1;

--negative revenue
SELECT *
FROM GOLD.FACT_SALES
WHERE TOTAL_AMOUNT <= 0;

--future dates
SELECT *
FROM GOLD.FACT_SALES
WHERE SALE_DATE > CURRENT_DATE();


--- connecting to Power BI for analysis

SELECT CURRENT_ORGANIZATION_NAME(),
       CURRENT_ACCOUNT(),
       CURRENT_REGION();

SHOW warehouses;